### PR TITLE
Created CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by theDevSoham**
This PR fixes issue #7 

I've added the necessary rules and regulations here along with local setup instructions. Please check and let me know if anything more is needed or anything is to be fixed here. Cheers!

### CODE REVIEW

**Review by Sadeedpv — CHANGES_REQUESTED** [review]
Remove the `Attribution` section at the end and there is no `Stlyeguides` & `Join The Project Team` section in the file, so it's better to remove those from the `Table of Contents`

**Comment by theDevSoham** [comment]
@Sadeedpv ahh apologies, missed that. Committing asap

**Comment by theDevSoham** [comment]
@Sadeedpv updated. Please check

**Review by Sadeedpv — CHANGES_REQUESTED** [review]
It would be better to remove the `Attributions` section at the end

**Comment by theDevSoham** [comment]
@Sadeedpv done

**Review by Sadeedpv — APPROVED** [review]

**Pull request merged**
